#! /usr/bin/env python
# coding=utf-8

"""
作者：刘旭萌
函数功能：分析周期为一天的恶意来源变化趋势
函数返回值为一个dataframe，第一列为date，第二列为当日出现且第二天消失的恶意来源个数
"""
import pandas as pd
import os

path = '../datanew/'
date_list = os.listdir(path)
try:
    temp = pd.read_csv('../data_final/get_period_change.csv')['date']
    date_old = temp.values.tolist()
except pd.errors.EmptyDataError:
    date_old = []

if len(date_old) != 0 and len(date_old) != 1:
    index = date_list.index(date_old[-2] + '.csv')
    date_list = date_list[index + 1:]
dtframe = []
for i in range(0, len(date_list)):
    try:
        dtframe.append(pd.read_csv(path + date_list[i])['ip'])
    except KeyError:
        dtframe.append(pd.read_csv(path + date_list[i]).iloc[0:, 0:1])
    dtframe[i] = pd.DataFrame(dtframe[i], columns=['ip']).drop_duplicates(keep='first')

period = pd.DataFrame()

for i in range(1, len(date_list) - 1):
    temp = dtframe[i - 1].append(dtframe[i]).append(dtframe[i + 1])
    temp.drop_duplicates(keep=False, inplace=True)
    period = period.append(pd.DataFrame({'date': [date_list[i][:-4]], 'num': [temp.shape[0]]}))

period.to_csv('../data_final/get_period_change.csv', sep=',', header=True, index=False , mode='a')
